USE [master]
GO

CREATE DATABASE [COVID-19]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COVID-19', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\COVID-19.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'COVID-19_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\COVID-19_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [COVID-19] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [COVID-19].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [COVID-19] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [COVID-19] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [COVID-19] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [COVID-19] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [COVID-19] SET ARITHABORT OFF 
GO
ALTER DATABASE [COVID-19] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [COVID-19] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [COVID-19] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [COVID-19] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [COVID-19] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [COVID-19] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [COVID-19] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [COVID-19] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [COVID-19] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [COVID-19] SET  DISABLE_BROKER 
GO
ALTER DATABASE [COVID-19] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [COVID-19] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [COVID-19] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [COVID-19] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [COVID-19] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [COVID-19] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [COVID-19] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [COVID-19] SET RECOVERY FULL 
GO
ALTER DATABASE [COVID-19] SET  MULTI_USER 
GO
ALTER DATABASE [COVID-19] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [COVID-19] SET DB_CHAINING OFF 
GO
ALTER DATABASE [COVID-19] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [COVID-19] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [COVID-19] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [COVID-19] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'COVID-19', N'ON'
GO
ALTER DATABASE [COVID-19] SET QUERY_STORE = OFF
GO
USE [COVID-19]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COVID_LOG](
	[COV_ID] [int] IDENTITY(1,1) NOT NULL,
	[VIS_ID] [int] NULL,
	[QUE_ID] [int] NULL,
	[ANSWER] [nchar](100) NULL,
	[LOG_DATETIME] [datetime] NULL,
	[LOC_ID] [int] NULL,
 CONSTRAINT [PK_COVID_LOG] PRIMARY KEY CLUSTERED 
(
	[COV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOCATION](
	[LOC_ID] [int] IDENTITY(1,1) NOT NULL,
	[SHORT_DESC] [nchar](15) NULL,
	[DESCRIPTION] [nchar](50) NULL,
 CONSTRAINT [PK_LOCATION] PRIMARY KEY CLUSTERED 
(
	[LOC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QUESTIONNAIRE](
	[QUE_ID] [int] IDENTITY(1,1) NOT NULL,
	[QUESTION] [nvarchar](max) NOT NULL,
	[ACTIVE] [bit] NOT NULL,
	[TYPE] [nchar](10) NULL,
	[QUE_NO] [int] NULL,
 CONSTRAINT [PK_QUESTIONNAIRE] PRIMARY KEY CLUSTERED 
(
	[QUE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VISITOR](
	[VIS_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nchar](50) NULL,
	[SURNAME] [nchar](50) NULL,
	[ID_NO] [nchar](15) NOT NULL,
	[GENDER] [nchar](10) NULL,
 CONSTRAINT [PK_VISITOR] PRIMARY KEY CLUSTERED 
(
	[VIS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COVID_LOG]  WITH CHECK ADD  CONSTRAINT [FK_COVID_LOG_LOCATION] FOREIGN KEY([LOC_ID])
REFERENCES [dbo].[LOCATION] ([LOC_ID])
GO
ALTER TABLE [dbo].[COVID_LOG] CHECK CONSTRAINT [FK_COVID_LOG_LOCATION]
GO
ALTER TABLE [dbo].[COVID_LOG]  WITH CHECK ADD  CONSTRAINT [FK_COVID_LOG_QUESTIONNAIRE] FOREIGN KEY([QUE_ID])
REFERENCES [dbo].[QUESTIONNAIRE] ([QUE_ID])
GO
ALTER TABLE [dbo].[COVID_LOG] CHECK CONSTRAINT [FK_COVID_LOG_QUESTIONNAIRE]
GO
ALTER TABLE [dbo].[COVID_LOG]  WITH CHECK ADD  CONSTRAINT [FK_COVID_LOG_VISITOR] FOREIGN KEY([VIS_ID])
REFERENCES [dbo].[VISITOR] ([VIS_ID])
GO
ALTER TABLE [dbo].[COVID_LOG] CHECK CONSTRAINT [FK_COVID_LOG_VISITOR]
GO
USE [master]
GO
ALTER DATABASE [COVID-19] SET  READ_WRITE 
GO
