USE [master]

CREATE DATABASE [SkipperLog]
GO


USE [SkipperLog]

CREATE TABLE [dbo].[Activity](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Activity] [nvarchar](50) NULL,
 CONSTRAINT [PK_Activity] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Boat](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[BoatName] [varchar](50) NULL,
	[BoatReg] [varchar](10) NULL,
	[BoatType] [varchar](30) NULL,
	[BoatLenght] [numeric](18, 0) NULL,
 CONSTRAINT [PK_Boat] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Logbook](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Date] [date] NOT NULL,
	[Venue_id] [int] NOT NULL,
	[Hours] [int] NOT NULL,
	[Activity_id] [int] NOT NULL,
	[Skipper_id] [int] NOT NULL,
	[Boat_id] [int] NOT NULL,
 CONSTRAINT [PK_Logbook] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Skippers](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Surname] [varchar](50) NULL,
	[LicenceType] [varchar](2) NULL,
 CONSTRAINT [PK_Skippers] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Venue](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Venue] [nvarchar](50) NULL,
	[Address] [nvarchar](max) NULL,
 CONSTRAINT [PK_Venue] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Logbook]  WITH CHECK ADD  CONSTRAINT [FK_Logbook_Activity] FOREIGN KEY([Activity_id])
REFERENCES [dbo].[Activity] ([id])
GO
ALTER TABLE [dbo].[Logbook] CHECK CONSTRAINT [FK_Logbook_Activity]
GO
ALTER TABLE [dbo].[Logbook]  WITH CHECK ADD  CONSTRAINT [FK_Logbook_Boat] FOREIGN KEY([Boat_id])
REFERENCES [dbo].[Boat] ([id])
GO
ALTER TABLE [dbo].[Logbook] CHECK CONSTRAINT [FK_Logbook_Boat]
GO
ALTER TABLE [dbo].[Logbook]  WITH CHECK ADD  CONSTRAINT [FK_Logbook_Skippers] FOREIGN KEY([Skipper_id])
REFERENCES [dbo].[Skippers] ([id])
GO
ALTER TABLE [dbo].[Logbook] CHECK CONSTRAINT [FK_Logbook_Skippers]
GO
ALTER TABLE [dbo].[Logbook]  WITH CHECK ADD  CONSTRAINT [FK_Logbook_Venue] FOREIGN KEY([Venue_id])
REFERENCES [dbo].[Venue] ([id])
GO
ALTER TABLE [dbo].[Logbook] CHECK CONSTRAINT [FK_Logbook_Venue]
GO
USE [master]
GO
ALTER DATABASE [SkipperLog] SET  READ_WRITE 
GO
