CREATE DATABASE [MyProperty]
GO

USE [MyProperty]
GO

CREATE TABLE VOTER_ADDRESS(id int primary key identity(1,1) not null,VOTER_ID varchar(50) not null,ADDRESS_1 varchar(20) null,ADDRESS_2 varchar(20) null,ADDRESS_3 varchar(20) null)

CREATE TABLE VOTING_STATIONS(id int primary key identity(1,1) not null,STATION_DESC varchar(100) not null,ADDRESS_1 varchar(20) null,ADDRESS_2 varchar(20) null,ADDRESS_3 varchar(20) null)

CREATE TABLE REGISTERED_PARTY(id int primary key identity(1,1) not null,CODE varchar(7),FULL_NAME varchar(20),LEADER varchar(20))

CREATE TABLE VOTER(id int primary key identity(1,1) not null,NAME varchar(50) not null,SURNAME varchar(50) not null,ID_NO varchar(10) not null,RACE varchar(10) not null,PARTY_ID int not null foreign key references REGISTERED_PARTY(id))

CREATE TABLE VOTER_ASSIGNMENT(id int primary key identity(1,1) not null,VOTER_id int foreign key references VOTER(id),STATION_id int foreign key references VOTING_STATIONS(id),ELECTION_YEAR INT,REGISTRATION_DATE DATE)

CREATE PROCEDURE UpdateVOTER_ADDRESS
@id int,
@VOTER_ID varchar(50),
@ADDRESS_1 varchar(20),
@ADDRESS_2 varchar(20),
@ADDRESS_3 varchar(20)
AS
UPDATE dbo.VOTER_ADDRESS
SET
VOTER_ID=@VOTER_ID,
ADDRESS_1=@ADDRESS_1,
ADDRESS_2=@ADDRESS_2,
ADDRESS_3=@ADDRESS_3
WHERE id=@id
GO

CREATE PROCEDURE UpdateVOTING_STATIONS
@id int,
@STATION_DESC varchar(100),
@ADDRESS_1 varchar(20),
@ADDRESS_2 varchar(20),
@ADDRESS_3 varchar(20)
AS
UPDATE dbo.VOTING_STATIONS
SET
STATION_DESC=@STATION_DESC,
ADDRESS_1=@ADDRESS_1,
ADDRESS_2=@ADDRESS_2,
ADDRESS_3=@ADDRESS_3
WHERE id=@id
GO

CREATE PROCEDURE UpdateREGISTERED_PARTY
@id int,
@CODE varchar(7),
@FULL_NAME varchar(20),
@LEADER varchar(20)
AS
UPDATE dbo.REGISTERED_PARTY
SET
CODE=@CODE,
FULL_NAME=@FULL_NAME,
LEADER=@LEADER
WHERE id=@id
GO

CREATE PROCEDURE UpdateVOTER
@id int,
@NAME varchar(50),
@SURNAME varchar(50),
@ID_NO varchar(10),
@RACE varchar(10),
@PARTY_ID INT
AS
UPDATE dbo.VOTER
SET
NAME=@NAME,
SURNAME=@SURNAME,
ID_NO=@ID_NO,
RACE=@RACE,
PARTY_ID=@PARTY_ID
WHERE id=@id
GO

CREATE PROCEDURE UpdateVOTER_ASSIGNMENT
@id int,
@VOTER_id int,
@STATION_id int,
@ELECTION_YEAR int,
@REGISTRATION_DATE DATE
AS
UPDATE dbo.VOTER_ASSIGNMENT
SET
VOTER_id=@VOTER_id,
STATION_id=@STATION_id
WHERE id=@id
GO

CREATE PROCEDURE DeleteVOTER_ASSIGNMENT
@id int,
@VOTER_id int,
@STATION_id int,
@ELECTION_YEAR int,
@REGISTRATION_DATE DATE
AS
DELETE FROM dbo.VOTER
WHERE id=@id
GO

CREATE PROCEDURE DeleteVOTER
@id int,
@NAME varchar(50),
@SURNAME varchar(50),
@ID_NO varchar(10),
@RACE varchar(10),
@PARTY_ID INT
AS
DELETE FROM dbo.VOTER
WHERE id=@id
GO

CREATE PROCEDURE DeleteREGISTERED_PARTY
@id int,
@CODE varchar(7),
@FULL_NAME varchar(20),
@LEADER varchar(20)
AS
DELETE FROM dbo.REGISTERED_PARTY
WHERE id=@id
GO

CREATE PROCEDURE DeleteVOTING_STATIONS
@id int,
@STATION_DESC varchar(100),
@ADDRESS_1 varchar(20),
@ADDRESS_2 varchar(20),
@ADDRESS_3 varchar(20)
AS
DELETE FROM dbo.VOTING_STATIONS
WHERE id=@id
GO

CREATE PROCEDURE DeleteVOTER_ADDRESS
@id int,
@VOTER_ID varchar(50),
@ADDRESS_1 varchar(20),
@ADDRESS_2 varchar(20),
@ADDRESS_3 varchar(20)
AS
DELETE FROM dbo.VOTER_ADDRESS
WHERE id=@id
Go

CREATE PROCEDURE CreateVOTER_ASSIGNMENT
@id int,
@VOTER_id int,
@STATION_id int,
@ELECTION_YEAR int,
@REGISTRATION_DATE DATE
AS
INSERT INTO dbo.VOTER_ASSIGNMENT(
VOTER_id,
STATION_id,
ELECTION_YEAR,
REGISTRATION_DATE)
VALUES
(@VOTER_id,@STATION_id,@ELECTION_YEAR,@REGISTRATION_DATE)
GO

CREATE PROCEDURE CreateVOTER
@id int,
@NAME varchar(50),
@SURNAME varchar(50),
@ID_NO varchar(10),
@RACE varchar(10),
@PARTY_ID INT
AS
INSERT INTO dbo.VOTER(
NAME,
SURNAME,
ID_NO,
RACE,
PARTY_ID)
VALUES
(@NAME,@SURNAME,@ID_NO,@RACE,@PARTY_ID)
GO

CREATE PROCEDURE CreateREGISTERED_PARTY
@id int,
@CODE varchar(7),
@FULL_NAME varchar(20),
@LEADER varchar(20)
AS
INSERT INTO dbo.REGISTERED_PARTY(
CODE,
FULL_NAME,
LEADER)
VALUES
(@CODE,@FULL_NAME,@LEADER)
GO

CREATE PROCEDURE CreateVOTING_STATIONS
@id int,
@STATION_DESC varchar(100),
@ADDRESS_1 varchar(20),
@ADDRESS_2 varchar(20),
@ADDRESS_3 varchar(20)
AS
INSERT INTO dbo.VOTING_STATIONS(
STATION_DESC,
ADDRESS_1,
ADDRESS_2,
ADDRESS_3)
VALUES
(@STATION_DESC,@ADDRESS_1,@ADDRESS_2,@ADDRESS_3)
GO

CREATE PROCEDURE CreateVOTER_ADDRESS
@id int,
@VOTER_ID varchar(50),
@ADDRESS_1 varchar(20),
@ADDRESS_2 varchar(20),
@ADDRESS_3 varchar(20)
AS
INSERT INTO dbo.VOTER_ADDRESS(
VOTER_ID,
ADDRESS_1,
ADDRESS_2,
ADDRESS_3)
VALUES
(@VOTER_ID,@ADDRESS_1,@ADDRESS_2,@ADDRESS_3)
GO

CREATE PROCEDURE GetVOTER_ASSIGNMENT
@id int,
@VOTER_id int,
@STATION_id int,
@ELECTION_YEAR int,
@REGISTRATION_DATE DATE
AS
IF @id != NULL
SELECT * FROM dbo.VOTER_ASSIGNMENT
WHERE id=@id
ELSE
SELECT * FROM dbo.VOTER_ASSIGNMENT

CREATE PROCEDURE GetVOTER
@id int,
@NAME varchar(50),
@SURNAME varchar(50),
@ID_NO varchar(10),
@RACE varchar(10),
@PARTY_ID INT
AS
IF @id != NULL
SELECT * FROM dbo.VOTER
WHERE id=@id
ELSE
SELECT * FROM dbo.VOTER

CREATE PROCEDURE GetREGISTERED_PARTY
@id int,
@CODE varchar(7),
@FULL_NAME varchar(20),
@LEADER varchar(20)
AS
IF @id != NULL
SELECT * FROM dbo.REGISTERED_PARTY
WHERE id=@id
ELSE
SELECT * FROM dbo.REGISTERED_PARTY

CREATE PROCEDURE GetVOTING_STATIONS
@id int,
@STATION_DESC varchar(100),
@ADDRESS_1 varchar(20),
@ADDRESS_2 varchar(20),
@ADDRESS_3 varchar(20)
AS
IF @id != NULL
SELECT * FROM dbo.VOTING_STATIONS
WHERE id=@id
ELSE
SELECT * FROM dbo.VOTING_STATIONS

CREATE PROCEDURE GetVOTER_ADDRESS
@id int,
@VOTER_ID varchar(50),
@ADDRESS_1 varchar(20),
@ADDRESS_2 varchar(20),
@ADDRESS_3 varchar(20)
AS
IF @id != NULL
SELECT * FROM dbo.VOTER_ADDRESS
WHERE id=@id
ELSE
SELECT * FROM dbo.VOTER_ADDRESS
