CREATE PROCEDURE GetContents
@CON_NAME varchar(50)
AS
IF @CON_NAME != NULL
SELECT * FROM dbo.CONTENT
WHERE CON_NAME=@CON_NAME
ELSE
SELECT * FROM dbo.CONTENT

CREATE PROCEDURE InsertContent
@CON_NAME varchar(50),
@CON_ID int,
@PRO_ID int,
@CON_DESCRIPTION varchar(100),
@CON_EXPIRE_DT datetime
AS
INSERT INTO dbo.CONTENT(
CON_NAME,
CON_ID,
PRO_ID,
CON_DESCRIPTION,
CON_EXPIRE_DT)
VALUES
(@CON_NAME,@CON_ID,@PRO_ID,@CON_DESCRIPTION,@CON_EXPIRE_DT)
GO

CREATE PROCEDURE UpdateContent
@CON_ID int,
@CON_Name varchar(50),
@PRO_ID int,
@CON_DESCRIPTION varchar(100),
@CON_EXPIRE_DT datetime
AS
UPDATE dbo.CONTENT
SET
CON_Name=@CON_Name,
PRO_ID=@PRO_ID,
CON_DESCRIPTION=@CON_DESCRIPTION,
CON_EXPIRE_DT=@CON_EXPIRE_DT
WHERE CON_ID=@CON_ID
GO

CREATE PROCEDURE DeleteContent
@CON_ID int
AS
DELETE FROM dbo.CONTENT
WHERE CON_ID=@CON_ID
GO