USE [master]
GO

CREATE DATABASE [VIEW-IT]
GO

USE [VIEW-IT]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONTENT](
	[CON_ID] [int] IDENTITY(1,1) NOT NULL,
	[PRO_ID] [int] NULL,
	[CON_NAME] [nvarchar](50) NULL,
	[CON_DESCRIPTION] [nvarchar](max) NULL,
	[CON_EXPIRE_DT] [date] NULL,
 CONSTRAINT [PK_CONTENT] PRIMARY KEY CLUSTERED 
(
	[CON_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTENT]  WITH CHECK ADD  CONSTRAINT [FK_CONTENT_PROVIDER] FOREIGN KEY([PRO_ID])
REFERENCES [dbo].[PROVIDER] ([PRO_ID])
GO

ALTER TABLE [dbo].[CONTENT] CHECK CONSTRAINT [FK_CONTENT_PROVIDER]
GO


CREATE TABLE [dbo].[PROVIDER](
	[PRO_ID] [int] IDENTITY(1,1) NOT NULL,
	[PRO_NAME] [nvarchar](50) NULL,
	[PRO_DESCRIPTION] [nvarchar](max) NULL,
	[PRO_URL] [nvarchar](max) NULL,
	[PRO_USERNAME] [nvarchar](50) NULL,
	[PRO_PASSWORD] [nvarchar](50) NULL,
	[PRO_STATUS] [bit] NULL,
 CONSTRAINT [PK_PROVIDER] PRIMARY KEY CLUSTERED 
(
	[PRO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[USERS](
	[USE_ID] [int] IDENTITY(1,1) NOT NULL,
	[USE_NAME] [nvarchar](50) NULL,
	[USE_PASSWORD] [nvarchar](50) NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[USE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[VIEW_HISTORY](
	[VIE_ID] [int] IDENTITY(1,1) NOT NULL,
	[CON_ID] [int] NOT NULL,
	[USE_ID] [int] NOT NULL,
	[VIE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_VIEW_HISTORY] PRIMARY KEY CLUSTERED 
(
	[VIE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VIEW_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_VIEW_HISTORY_CONTENT] FOREIGN KEY([CON_ID])
REFERENCES [dbo].[CONTENT] ([CON_ID])
GO

ALTER TABLE [dbo].[VIEW_HISTORY] CHECK CONSTRAINT [FK_VIEW_HISTORY_CONTENT]
GO

ALTER TABLE [dbo].[VIEW_HISTORY]  WITH CHECK ADD  CONSTRAINT [FK_VIEW_HISTORY_USERS] FOREIGN KEY([USE_ID])
REFERENCES [dbo].[USERS] ([USE_ID])
GO

ALTER TABLE [dbo].[VIEW_HISTORY] CHECK CONSTRAINT [FK_VIEW_HISTORY_USERS]
GO



